### ISSUE TITLE
Ability to have templated files

### ISSUE THREAD

**Issue by vNicolini** [masqu3rad3/tik_manager4#107]
**Is your feature request related to a problem? Please describe.**
Missing templated files creation/handling. 

**Describe the solution you'd like**
It would be nice to have the ability to create files (especially for v0001) based on pre-existing template.

Especially in the context of surfacing, comp and lighting where templates allows to get to actually work right away instead of fiddling for couples of minutes (or hours) for every asset or every shot. Which is even more true in softwares such as Katana, Gaffer, Houdini/Solaris or Nuke. 

See attached an exemple of how it's handled from the user point of view in Prisp Pipeline (which is what i currently am using but considering switching to TikManager because of the Katana and Gaffer integration), hopefully it'll help understand what feature i'm talking about. 

Let me know if it isn't clear enough!

https://github.com/masqu3rad3/tik_manager4/assets/57097563/42c4f010-a3bf-4539-9bf1-c15b52785983

**Comment by masqu3rad3** [comment]
@vNicolini  I am thinking about 3 levels (folders) to collect the template files:

high level --> user defined directory - Will be defined from the settings / user section. Each user can have its own.
mid level --> project level templates - will look for the _templates directory under the current project root.
low level --> common level templates - will look for the _templates directory under the common folder.

Each level will be an update for the previous level. For example if LookDevTemplate_Prman.katana exists both in project templates and user templates it will pick up the user defined one.

What do you think? Is it over-kill?

**Comment by vNicolini** [comment]
Hey,
i like this idea! Although i'm wondering if the prio order shouldn't be shuffled, or ideally (but not sure how complex it would be to put in place), let the user define the priority level themselves either globaly (eg: common level) or per project. 

Hope that makes sense!

**Comment by vNicolini** [comment]
Makes perfect sense and seems fairly logical to me.

The templates should only really impact the first version of each asset/task anyway. 

Have you thought about how said template would be loaded in/created (moved and renamed accordingly) within Tik4 workflow ? 
Unless you have a custom launcher with Tik4 that resolves current project, asset (sub-project), task and department (works) i'm not sure what's the plan ... 

What Prism do, and what i think is "best" from an individual standpoint is the ability to manually create new work files from the main UI (inside and outside an integration) based on pre-existing templates files (see video from original post). 

Sure from a pure production standpoint "everything" should be handled within the pipeline with automation though.

**Comment by masqu3rad3** [comment]
I first thought about adding it as a dropdown menu to the 'Save Work' Dialog. 
If an item from the available templates list selected, it would do the copy/rename action you described.

However, on a second thought I think it will be a bit confusing since it won't be explicit and user may be thinking that the current scene is getting saved.

So I am thinking a dedicated a button (Save Work From Template - or similar) in the main UI and a mini-dialog for it.

**Comment by vNicolini** [comment]
> So I am thinking a dedicated a button (Save Work From Template - or similar) in the main UI and a mini-dialog for it.

That would mean you already have opened the template somehow **and** hopefully didn't do anything and saved on top of the pre-existing template, if that makes sense...

Hence why i'd personally prefer to be able to create a work file **from** a template list in the Main UI (be it in DCC or on desktop) to then open/load the newly created file in the DCC. 

Else how do you know which template to load and when?

That currently is how i approach it with Prism and Katana (which doesn't have any integration with Prism whatsoever, but the process is the same with all DCCs): 

https://github.com/masqu3rad3/tik_manager4/assets/57097563/1758f8fa-a59c-49dc-92ef-f86b3f2e0a2b

**Comment by masqu3rad3** [comment]
I probably couldn't explain it. We are not touching templates. Templates are never getting opened by user.

What I described was extremely similar to what you are doing there. Only thing I am proposing a menu button to bring up a ui where you can select the template instead of right click menu (additionally right click menu can be present too)

**Comment by vNicolini** [comment]
Oh okay, then i misread/misunderstood! 

All good and sorry for the confusion!!

**Comment by masqu3rad3** [comment]
Okay, I am almost finished. However I am changing the resolution order again (promise this is last time)

So Tik Manager will collect the template files from:
- `<project root>/ _templates` folder (doesn't need to exist)
- `<common folder>/_templates` folder (doesn't need to exist)
- a folder defined by user (can changed from settings)

It will only collect acceptable extensions (for all DCCs)
If a file with the same name exist on multiple locations, the resolution order will be project > common > user

I reached the conclusion project should have the top most priority since it should be override the common. Imagine there are several projects using the different versions of dccs. In that case even the 'empty' files should ideally match the project defined DCC versions.
