### ISSUE TITLE
[Substance Painter] Select channels, format and resolution to export 

### ISSUE THREAD

**Issue by vNicolini** [masqu3rad3/tik_manager4#115]
**Is your feature request related to a problem? Please describe.**
I noticed that in Substance when publishing the maps bundle it doesn't offer any control over which channel can/should be taken into account for the export, which format (i'm fine with EXR all the way!) and bit depth as well as the resolution.
In the test i ran, i just had baked my mesh maps and i was expecting to be able to export them right away but it only exported the channels of the shader. 

**Describe the solution you'd like**
Add parameters (or customizable presets) to be able to choose/control the following values:
- file format
- bit depth
- resolution
- colorspace 
- toggles for which channel(s) to export

Cheers,
VNI

PS: _I slowly am testing "every" integration i "need" in my workflow/pipeline, sorry if i spam you with issues/FR_

**Comment by masqu3rad3** [comment]
Can you elaborate this bit? What is the other alternative or expected behaviour?
 _i was expecting to be able to export them right away but it only exported the channels of the shader._

Sorry I am a total newbie with Substance, Katana, Mari and Gaffer. I actually install them for the first time with this Tik Manager project.

I think the best implementation would be a mixture of exposing the parameters and setting them as metadata.
For example, this can be exposed but the default values can be taken from the metadata (if exists)
I think I did something similar in one of the extractors in Maya.

Regarding the ingestors and extracts, I really want to keep it at bare minimum, but encourage TDs to add their custom extracts and ingests according to their pipeline requirements.

Otherwise one of the two things will likely happen:
Either there will be bunch of options that the user needs to be aware of and adjust all the time, which can easily become slower than doing it manually.
Or it will evolve to a very specific pipeline which few people would agree.
I am trying find a balance between.

Don't worry about flooding the issues, I just cannot promise I can do all of them or at the same time :)

**Comment by vNicolini** [comment]
> I think the best implementation would be a mixture of exposing the parameters and setting them as metadata.
For example, this can be exposed but the default values can be taken from the metadata (if exists)

I think that would be a good middle ground, giving "enough" for the non-TD to "just work" but without sacrificing the customizability for more technical users/artists (eg: TDs).

When using tools like Tik, Prism or any pipeline really, it kinda is a "set and forget" approach on the user end. Having sensible default with the ability to customize would be the path to take imo.

I'd be happy to provide opinions on how things can/should be set by default and/or dealt with on Katana/Substance/Gaffer. 

What i can suggest too is for you to join Katana/Gaffer/Mari's _official_ discord server if you haven't already.
I'm sure you'll be able to find some more information (potentially more accurate than mine too) on how to approach exposed control vs hidden control, default values, etc .....

> I just cannot promise I can do all of them or at the same time :)

Ahahah no worries! That's understandable!

Cheers, 
VNI
