### ISSUE TITLE
Delete specific version from Work & Import File/Folder as Version for Selected Work

### ISSUE THREAD

**Issue by onlykshitij** [masqu3rad3/tik_manager4#140]
I was looking around learning the tool and couldn't find a way to remove a version of work. I would like to avoid removing the entire work to remove a version.

I would also love to be able to simply import files for versions (just like it is available to make new works) so that I can make works for file types that aren't necessarily linked to a DCC.

**Comment by masqu3rad3** [comment]
Hi,

Both these functionalities are already available with the right click context.

To Remove a version of a work (or publish) right-click the version number under the Versions section and select 'Delete Version'

![image](https://github.com/user-attachments/assets/0f38ab97-5f18-4c22-a4ec-f2c3b4ca173d)

Similarly you can import from other works with the right click menu from the 'Works' section. For this, you need to right click a 'work' and select import.

![image](https://github.com/user-attachments/assets/31816f47-c249-4f4f-8861-d85168c07b7d)

**Comment by onlykshitij** [comment]
Hi, thanks for replying!

Great to see Deleting version is available. 
I think I'll rephrase what I meant by Importing File/Folder as new version.

I meant being able to import a file from a directory as a version for a work.
Example: I have a set of Concept Art files in png format that aren't made in Photoshop (hence can't directly use Tik Manager). If possible, I would like to simply create a new version of existing work by importing a file from a directory (similar to how I can go to File -> Import File as work)

**Comment by masqu3rad3** [comment]
In this case, you can simply drag and drop any file to the tik manager UI to make a snapshot work save.
If you want to snapshot publish the same file (to protect and pass it down the line) you just need to 
 
![peek](https://github.com/user-attachments/assets/2ff3a67c-3d7a-456f-85b3-aa188358e15e)

 However, mixing and matching the version iterations with saving through tik manager and drag and drop is not possible and it is also not safe since the version and fps checks wouldn't be possible and it can easily create a big mess.

**Comment by onlykshitij** [comment]
I see, thank you very much, for both the tool and the replies! I look forward to hopefully more people contributing towards this project.
